name: task_manager_flutter_app
description: "A new Flutter project."
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  get: ^4.6.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^8.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

 
