# Generated by Django 5.1.3 on 2025-01-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_thrill_app', '0002_customuser_phone_number_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
