# Generated by Django 5.1.3 on 2025-01-11 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_thrill_app', '0004_task_due_date_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
