### Sign up endpoint
POST http://127.0.0.1:8000/api/signup/
Content-Type: application/json

{
  "username": "clementdevv",
  "email": "clementdevv@gmail.com",
  "password": "sec!",
  "first_name": "clement",
  "last_name": "devv"
}

###

### Log in endpoint
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
  "email": "clementdevv@gmail.com",
  "password": "sec!"
}

### create task
POST http://127.0.0.1:8000/api/tasks/create/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2Njk5Mzg5LCJpYXQiOjE3MzY2OTg0ODksImp0aSI6Ijg0NGQyZmNlNTE2NDRiZDc5MjdiOTU5MzBjNGM4Mzk4IiwidXNlcl9pZCI6MX0.7YQxvsQRtrOqyWfudAgAEQlRMIoXuq8EkcumWZRVDjw

{
  "title": "Sample Task",
  "description": "This is a test task.",
  "priority": "low",
  "start_time": "2025-01-12 09:00:00",  
  "end_time": "2025-01-15 17:00:00" 
}

###view all tasks
GET http://127.0.0.1:8000/api/tasks/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2Njk5Mzg5LCJpYXQiOjE3MzY2OTg0ODksImp0aSI6Ijg0NGQyZmNlNTE2NDRiZDc5MjdiOTU5MzBjNGM4Mzk4IiwidXNlcl9pZCI6MX0.7YQxvsQRtrOqyWfudAgAEQlRMIoXuq8EkcumWZRVDjw

###update tasks
PUT http://127.0.0.1:8000/api/tasks/1/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2Njk5Mzg5LCJpYXQiOjE3MzY2OTg0ODksImp0aSI6Ijg0NGQyZmNlNTE2NDRiZDc5MjdiOTU5MzBjNGM4Mzk4IiwidXNlcl9pZCI6MX0.7YQxvsQRtrOqyWfudAgAEQlRMIoXuq8EkcumWZRVDjw

{
  "title": "Work",
  "description": "Got to work",
  "priority": "high",
  "start_time": "2025-02-17 09:00:00",  
  "end_time": "2025-02-20 17:00:00"
}

###delete tasks
DELETE http://127.0.0.1:8000/api/tasks/3/delete/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2Njk5Mzg5LCJpYXQiOjE3MzY2OTg0ODksImp0aSI6Ijg0NGQyZmNlNTE2NDRiZDc5MjdiOTU5MzBjNGM4Mzk4IiwidXNlcl9pZCI6MX0.7YQxvsQRtrOqyWfudAgAEQlRMIoXuq8EkcumWZRVDjw

