### Sign up endpoint
POST http://127.0.0.1:8000/api/signup/
Content-Type: application/json

{
  "username": "clementdevv",
  "email": "clementdevv@gmail.com",
  "password": "sec!",
  "first_name": "clement",
  "last_name": "devv"
}

###

### Log in endpoint
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
  "email": "clementdevv@gmail.com",
  "password": "sec!"
}

### create task
POST http://127.0.0.1:8000/api/tasks/create/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2Njg2MzQ0LCJpYXQiOjE3MzY2ODU0NDQsImp0aSI6ImYxMzA3ZmRjMzU2NTQ4Nzg4YWI4ZjBlMzQzYTgzZjQ3IiwidXNlcl9pZCI6MX0.UwTySIIFTK3hCctP4K0i3f_w-kTi2mx9TGu_XarsMh4

{
  "title": "Sample Task",
  "description": "This is a test task.",
  "priority": "low",
  "start_time": "2025-01-12 09:00:00",  
  "end_time": "2025-01-15 17:00:00" 
}

###view all tasks
GET http://127.0.0.1:8000/api/tasks/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2Njg2MzQ0LCJpYXQiOjE3MzY2ODU0NDQsImp0aSI6ImYxMzA3ZmRjMzU2NTQ4Nzg4YWI4ZjBlMzQzYTgzZjQ3IiwidXNlcl9pZCI6MX0.UwTySIIFTK3hCctP4K0i3f_w-kTi2mx9TGu_XarsMh4

###update tasks
PUT http://127.0.0.1:8000/api/tasks/4/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2Njg2MzQ0LCJpYXQiOjE3MzY2ODU0NDQsImp0aSI6ImYxMzA3ZmRjMzU2NTQ4Nzg4YWI4ZjBlMzQzYTgzZjQ3IiwidXNlcl9pZCI6MX0.UwTySIIFTK3hCctP4K0i3f_w-kTi2mx9TGu_XarsMh4

{
  "title": "Work",
  "description": "Got to work",
   "priority": "high",
  "start_time": "2025-02-12 09:00:00",  
  "end_time": "2025-02-15 17:00:00"
}

###delete tasks
DELETE http://127.0.0.1:8000/api/tasks/4/delete/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2Njg2MzQ0LCJpYXQiOjE3MzY2ODU0NDQsImp0aSI6ImYxMzA3ZmRjMzU2NTQ4Nzg4YWI4ZjBlMzQzYTgzZjQ3IiwidXNlcl9pZCI6MX0.UwTySIIFTK3hCctP4K0i3f_w-kTi2mx9TGu_XarsMh4

